// Generated by FlightFabric. Reinstall the toolbar package from FlightFabric
// Settings if the FlightFabric network ports change.
window.FLIGHTFABRIC_TOOLBAR_CONFIG = Object.freeze({
  httpPort: __FF_HTTP_PORT__,
  wsPort: __FF_WS_PORT__,
  packageVersion: "0.11.0",
});
