/**
 * Landing CSV Contract - bridge between landing-runner payloads and V1 CSV rows.
 *
 * Landing detection emits a rich event-bus payload. The CSV writer only persists
 * fields that `schema-field-map.ts` knows how to extract, so this module names
 * the landing fields that must survive that boundary and supplies aliases used
 * by the writer/schema (`vs`, `gForce`, `event_id`, and friends). Tests use this
 * list as a guard against adding landing diagnostics that never make it into
 * the recorded CSV.
 */
'use strict';

type GenericRecord = Record<string, any>;
type FieldMapping = {
  payloadKey: string;
  column: string;
};

const CRITICAL_LANDING_CSV_MAPPINGS: readonly FieldMapping[] = Object.freeze([
  { payloadKey: 'schema_version', column: 'schema_version' },
  { payloadKey: 'user_id', column: 'user_id' },
  { payloadKey: 'session_id', column: 'session_id' },
  { payloadKey: 'timestamp_ms', column: 'ts' },
  { payloadKey: 'timestamp_utc', column: 'timestamp_utc' },
  { payloadKey: 'flight_start', column: 'flight_start_iso' },
  { payloadKey: 'flight_elapsed_ms', column: 'flight_elapsed_ms' },
  { payloadKey: 'aircraft', column: 'aircraft' },
  { payloadKey: 'sim_version', column: 'sim_version' },
  { payloadKey: 'aircraft_profile_id', column: 'aircraft_profile_id' },
  { payloadKey: 'data_source', column: 'data_source' },
  { payloadKey: 'assist_unlimited_fuel', column: 'assist_unlimited_fuel' },
  { payloadKey: 'assist_landing_enabled', column: 'assist_landing_enabled' },
  { payloadKey: 'assist_takeoff_enabled', column: 'assist_takeoff_enabled' },
  { payloadKey: 'assist_ai_controls', column: 'assist_ai_controls' },
  { payloadKey: 'assist_ai_autotrim', column: 'assist_ai_autotrim' },
  { payloadKey: 'assist_ai_delegated', column: 'assist_ai_delegated' },
  { payloadKey: 'assist_ai_antistall_state', column: 'assist_ai_antistall_state' },
  { payloadKey: 'assist_ai_antistall_active', column: 'assist_ai_antistall_active' },
  { payloadKey: 'assist_realism_pct', column: 'assist_realism_pct' },
  { payloadKey: 'assist_full_realism', column: 'assist_full_realism' },
  { payloadKey: 'assist_slew_active', column: 'assist_slew_active' },
  { payloadKey: 'assist_any_active', column: 'assist_any_active' },
  { payloadKey: 'icao', column: 'icao' },
  { payloadKey: 'runway', column: 'runway' },
  { payloadKey: 'approach_type', column: 'approach_type' },
  { payloadKey: 'vs_fpm', column: 'vs_fpm' },
  { payloadKey: 'ias_kts', column: 'ias_kts' },
  { payloadKey: 'gs_kts', column: 'gs_kts' },
  { payloadKey: 'grade', column: 'grade' },
  { payloadKey: 'gforce', column: 'g_force' },
  { payloadKey: 'lat_deg', column: 'lat_deg' },
  { payloadKey: 'lon_deg', column: 'lon_deg' },
  { payloadKey: 'hdg_true_deg', column: 'hdg_true_deg' },
  { payloadKey: 'hdg_mag_deg', column: 'hdg_mag_deg' },
  { payloadKey: 'alt_msl_ft', column: 'alt_msl_ft' },
  { payloadKey: 'alt_indicated_ft', column: 'alt_indicated_ft' },
  { payloadKey: 'alt_calibrated_ft', column: 'alt_calibrated_ft' },
  { payloadKey: 'alt_plane_ft', column: 'alt_plane_ft' },
  { payloadKey: 'ra_ft', column: 'ra_ft' },
  { payloadKey: 'aircraft_agl_ft', column: 'aircraft_agl_ft' },
  { payloadKey: 'aircraft_above_obstacles_ft', column: 'aircraft_above_obstacles_ft' },
  { payloadKey: 'plane_agl_ft', column: 'plane_agl_ft' },
  { payloadKey: 'plane_agl_minus_cg_ft', column: 'plane_agl_minus_cg_ft' },
  { payloadKey: 'pressure_alt_ft', column: 'pressure_alt_ft' },
  { payloadKey: 'kohlsman_setting_mb', column: 'kohlsman_setting_mb' },
  { payloadKey: 'kohlsman_tuned_mb', column: 'kohlsman_tuned_mb' },
  { payloadKey: 'kohlsman_std', column: 'kohlsman_std' },
  { payloadKey: 'wind_speed_kts', column: 'wind_speed_kts' },
  { payloadKey: 'wind_dir_deg', column: 'wind_dir_deg' },
  { payloadKey: 'xwind_kts', column: 'xwind_kts' },
  { payloadKey: 'pitch_deg', column: 'pitch_deg' },
  { payloadKey: 'bank_deg', column: 'bank_deg' },
  { payloadKey: 'touchdown_capture_source', column: 'touchdown_capture_source' },
  { payloadKey: 'td_sim_source', column: 'td_sim_source' },
  { payloadKey: 'td_sim_trusted', column: 'td_sim_trusted' },
  { payloadKey: 'td_sim_fresh', column: 'td_sim_fresh' },
  { payloadKey: 'td_sim_reject_reason', column: 'td_sim_reject_reason' },
  { payloadKey: 'td_sim_position_delta_ft', column: 'td_sim_position_delta_ft' },
  { payloadKey: 'td_sim_lat_deg', column: 'td_sim_lat_deg' },
  { payloadKey: 'td_sim_lon_deg', column: 'td_sim_lon_deg' },
  { payloadKey: 'td_sim_hdg_true_deg', column: 'td_sim_hdg_true_deg' },
  { payloadKey: 'td_sim_hdg_mag_deg', column: 'td_sim_hdg_mag_deg' },
  { payloadKey: 'td_sim_pitch_deg', column: 'td_sim_pitch_deg' },
  { payloadKey: 'td_sim_bank_deg', column: 'td_sim_bank_deg' },
  { payloadKey: 'td_sim_normal_velocity_fps', column: 'td_sim_normal_velocity_fps' },
  { payloadKey: 'td_sim_normal_velocity_fpm', column: 'td_sim_normal_velocity_fpm' },
  { payloadKey: 'td_sim_landing_vs_fpm', column: 'td_sim_landing_vs_fpm' },
  { payloadKey: 'flaps_notch', column: 'flaps_notch' },
  { payloadKey: 'spoiler_state', column: 'spoiler_state' },
  { payloadKey: 'phase', column: 'phase' },
  { payloadKey: 'stability', column: 'stability' },
  { payloadKey: 'ultimate_stability_score', column: 'ultimate_stability_score' },
  { payloadKey: 'ultimate_stability_samples', column: 'ultimate_stability_samples' },
  { payloadKey: 'ultimate_stability_gate_stable', column: 'ultimate_stability_gate_stable' },
  { payloadKey: 'ultimate_stability_gate_failures', column: 'ultimate_stability_gate_failures' },
  { payloadKey: 'ultimate_stability_breakdown', column: 'ultimate_stability_breakdown' },
  { payloadKey: 'ultimate_stability_context', column: 'ultimate_stability_context' },
  { payloadKey: 'ultimate_stability_gear_ok_pct', column: 'ultimate_stability_gear_ok_pct' },
  { payloadKey: 'ultimate_stability_flaps_ok_pct', column: 'ultimate_stability_flaps_ok_pct' },
  { payloadKey: 'ultimate_stability_spoilers_ok_pct', column: 'ultimate_stability_spoilers_ok_pct' },
  { payloadKey: 'ultimate_stability_config_ok_pct', column: 'ultimate_stability_config_ok_pct' },
  { payloadKey: 'ultimate_stability_speed_ok_pct', column: 'ultimate_stability_speed_ok_pct' },
  { payloadKey: 'ultimate_stability_speed_trend_ok_pct', column: 'ultimate_stability_speed_trend_ok_pct' },
  { payloadKey: 'ultimate_stability_vs_ok_pct', column: 'ultimate_stability_vs_ok_pct' },
  { payloadKey: 'ultimate_stability_glidepath_ok_pct', column: 'ultimate_stability_glidepath_ok_pct' },
  { payloadKey: 'ultimate_stability_glidepath_below_ok_pct', column: 'ultimate_stability_glidepath_below_ok_pct' },
  { payloadKey: 'ultimate_stability_glidepath_above_ok_pct', column: 'ultimate_stability_glidepath_above_ok_pct' },
  { payloadKey: 'ultimate_stability_thrust_ok_pct', column: 'ultimate_stability_thrust_ok_pct' },
  { payloadKey: 'ultimate_stability_thrust_not_idle_ok_pct', column: 'ultimate_stability_thrust_not_idle_ok_pct' },
  { payloadKey: 'ultimate_stability_thrust_stable_ok_pct', column: 'ultimate_stability_thrust_stable_ok_pct' },
  { payloadKey: 'ultimate_stability_pitch_ok_pct', column: 'ultimate_stability_pitch_ok_pct' },
  { payloadKey: 'ultimate_stability_bank_ok_pct', column: 'ultimate_stability_bank_ok_pct' },
  { payloadKey: 'ultimate_stability_lateral_offset_ok_pct', column: 'ultimate_stability_lateral_offset_ok_pct' },
  { payloadKey: 'surface_raw', column: 'surface_raw' },
  { payloadKey: 'surface_name', column: 'surface_name' },
  { payloadKey: 'surface_class', column: 'surface_class' },
  { payloadKey: 'surface_runway_like', column: 'surface_runway_like' },
  { payloadKey: 'surface_on_runway', column: 'surface_on_runway' },
  { payloadKey: 'surface_on_ground', column: 'surface_on_ground' },
  { payloadKey: 'surface_valid', column: 'surface_valid' },
  { payloadKey: 'runway_excursion', column: 'runway_excursion' },
  { payloadKey: 'runway_occupancy_s', column: 'runway_occupancy_s' },
  { payloadKey: 'rollout_analysis', column: 'rollout_analysis' },
  { payloadKey: 'landing_final', column: 'landing_final' },
  { payloadKey: 'fdm_surface_condition', column: 'fdm_surface_condition' },
  { payloadKey: 'fdm_precip_state', column: 'fdm_precip_state' },
  { payloadKey: 'fdm_precip_rate_mm', column: 'fdm_precip_rate_mm' },
  { payloadKey: 'fdm_oat_c', column: 'fdm_oat_c' },
  { payloadKey: 'touchdown_distance_ft', column: 'touchdown_distance_ft' },
  { payloadKey: 'runway_geometry_source', column: 'runway_geometry_source' },
  { payloadKey: 'runway_geometry_provider_chain', column: 'runway_geometry_provider_chain' },
  { payloadKey: 'runway_geometry_fallback_reason', column: 'runway_geometry_fallback_reason' },
  { payloadKey: 'runway_geometry_diagnostics', column: 'runway_geometry_diagnostics' },
  { payloadKey: 'runway_heading_true_deg', column: 'runway_heading_true_deg' },
  { payloadKey: 'runway_length_ft', column: 'runway_length_ft' },
  { payloadKey: 'runway_physical_length_ft', column: 'runway_physical_length_ft' },
  { payloadKey: 'runway_surface', column: 'runway_surface' },
  { payloadKey: 'runway_threshold_lat', column: 'runway_threshold_lat' },
  { payloadKey: 'runway_threshold_lon', column: 'runway_threshold_lon' },
  { payloadKey: 'runway_physical_threshold_lat', column: 'runway_physical_threshold_lat' },
  { payloadKey: 'runway_physical_threshold_lon', column: 'runway_physical_threshold_lon' },
  { payloadKey: 'runway_displaced_threshold_ft', column: 'runway_displaced_threshold_ft' },
  { payloadKey: 'touchdown_distance_score', column: 'touchdown_distance_score' },
  { payloadKey: 'touchdown_distance_grade', column: 'touchdown_distance_grade' },
  { payloadKey: 'short_landing', column: 'short_landing' },
  { payloadKey: 'runway_condition', column: 'runway_condition' },
  { payloadKey: 'runway_condition_source', column: 'runway_condition_source' },
  { payloadKey: 'runway_condition_confident', column: 'runway_condition_confident' },
  { payloadKey: 'lateral_offset_ft', column: 'lateral_offset_ft' },
  { payloadKey: 'lateral_offset_side', column: 'lateral_offset_side' },
  { payloadKey: 'lateral_offset_score', column: 'lateral_offset_score' },
  { payloadKey: 'lateral_offset_grade', column: 'lateral_offset_grade' },
  { payloadKey: 'lateral_offset_suspect', column: 'lateral_offset_suspect' },
  { payloadKey: 'runway_width_ft', column: 'runway_width_ft' },
  { payloadKey: 'bounce_count', column: 'bounce_count' },
  { payloadKey: 'bounce_grade', column: 'bounce_grade' },
  { payloadKey: 'bounce_score', column: 'bounce_score' },
  { payloadKey: 'bounce_distance_ft', column: 'bounce_distance_ft' },
  { payloadKey: 'bounce_worst_gforce', column: 'bounce_worst_gforce' },
  { payloadKey: 'first_touchdown_lat', column: 'first_touchdown_lat' },
  { payloadKey: 'first_touchdown_lon', column: 'first_touchdown_lon' },
  { payloadKey: 'first_touchdown_vs_fpm', column: 'first_touchdown_vs_fpm' },
  { payloadKey: 'first_touchdown_gforce', column: 'first_touchdown_gforce' },
  { payloadKey: 'final_touchdown_lat', column: 'final_touchdown_lat' },
  { payloadKey: 'final_touchdown_lon', column: 'final_touchdown_lon' },
  { payloadKey: 'final_touchdown_vs_fpm', column: 'final_touchdown_vs_fpm' },
  { payloadKey: 'final_touchdown_gforce', column: 'final_touchdown_gforce' },
]);

function getCriticalLandingCsvMappings(): FieldMapping[] {
  return CRITICAL_LANDING_CSV_MAPPINGS.map((mapping) => ({ ...mapping }));
}

function buildLandingCsvEventData(payload: GenericRecord | null | undefined, eventId: string): GenericRecord {
  const source = payload && typeof payload === 'object' ? payload : {};
  const resolvedEventId = eventId || source.eventId || source.event_id || null;
  return {
    ...source,
    eventId: resolvedEventId,
    event_id: resolvedEventId,
    vs: source.vs_fpm ?? source.vs ?? null,
    ias: source.ias_kts ?? source.ias ?? null,
    gForce: source.gforce ?? source.gForce ?? null,
    onGround: source.on_ground ?? source.onGround ?? true,
    flightPhaseHint: source.flightPhaseHint ?? source.flight_phase_hint ?? source.phase ?? null,
    flight_phase_hint: source.flight_phase_hint ?? source.flightPhaseHint ?? source.phase ?? null,
    phase: 'LANDING',
  };
}

module.exports = {
  CRITICAL_LANDING_CSV_MAPPINGS,
  buildLandingCsvEventData,
  getCriticalLandingCsvMappings,
};

export {};
