// Generated by scripts/build-toolbar-presets.mjs. Do not edit.
var FlightFabricToolbarPresets = (() => {
  var __create = Object.create;
  var __defProp = Object.defineProperty;
  var __defProps = Object.defineProperties;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropDescs = Object.getOwnPropertyDescriptors;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __getOwnPropSymbols = Object.getOwnPropertySymbols;
  var __getProtoOf = Object.getPrototypeOf;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __propIsEnum = Object.prototype.propertyIsEnumerable;
  var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
  var __spreadValues = (a, b) => {
    for (var prop in b || (b = {}))
      if (__hasOwnProp.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    if (__getOwnPropSymbols)
      for (var prop of __getOwnPropSymbols(b)) {
        if (__propIsEnum.call(b, prop))
          __defNormalProp(a, prop, b[prop]);
      }
    return a;
  };
  var __spreadProps = (a, b) => __defProps(a, __getOwnPropDescs(b));
  var __commonJS = (cb, mod) => function __require() {
    return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
  };
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
    // If the importer is in node compatibility mode or this is not an ESM
    // file that has been converted to a CommonJS file using a Babel-
    // compatible transform (i.e. "__esModule" has not been set), then set
    // "default" to the CommonJS "module.exports" for node compatibility.
    isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
    mod
  ));
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // shared/aircraft-presets.js
  var require_aircraft_presets = __commonJS({
    "shared/aircraft-presets.js"(exports, module) {
      (function(root) {
        "use strict";
        var LIGHT_ORDER = ["configuration.lights.takeoff", "configuration.lights.afterTakeoff", "configuration.lights.landing", "configuration.lights.afterLanding"];
        var SOURCE_FIELDS = [
          "lights.landing",
          "lights.noseMode",
          "lights.strobeMode",
          "lights.nav",
          "lights.navMode",
          "lights.landingLeftPosition",
          "lights.landingRightPosition",
          "lights.nosePosition",
          "lights.turnoffLeft",
          "lights.turnoffRight",
          "lights.strobe",
          "systems.busVoltage",
          "systems.apuMaster",
          "systems.apuStart",
          "systems.apuAvailable",
          "systems.apuMasterFault",
          "mcp.courseCaptainDeg",
          "mcp.courseFirstOfficerDeg",
          "radios.nav1ActiveMhz",
          "radios.nav2ActiveMhz"
        ];
        function groups(commands) {
          var list = (Array.isArray(commands) ? commands : Object.values(commands || {})).filter(function(command) {
            return command && command.kind === "preset" && command.input && ["none", "number"].includes(command.input.kind);
          });
          var light = function(command) {
            return command.id.startsWith("configuration.lights.");
          };
          var brightness = function(command) {
            return command.id.startsWith("configuration.lighting.");
          };
          return {
            cards: list.filter(function(command) {
              return !light(command) && !brightness(command);
            }),
            lights: list.filter(light).sort(function(a, b) {
              var order = function(c) {
                var i = LIGHT_ORDER.indexOf(c.id);
                return i < 0 ? LIGHT_ORDER.length : i;
              };
              return order(a) - order(b) || a.id.localeCompare(b.id);
            }),
            brightness: ["configuration.lighting.cockpit", "configuration.lighting.displays"].map(function(id) {
              return list.find(function(command) {
                return command.id === id;
              });
            }).filter(Boolean)
          };
        }
        function numberValue(command, draft) {
          var text = String(draft === void 0 ? "" : draft).trim(), input = command.input || {};
          if (!text) return null;
          var value = Number(text), position = (value - input.min) / input.step;
          return Number.isFinite(value) && value >= input.min && value <= input.max && Math.abs(position - Math.round(position)) < 1e-7 ? value : null;
        }
        function brightnessLabel2(id) {
          return id === "configuration.lighting.cockpit" ? "Global cockpit lighting" : "All flight displays";
        }
        function readbackFields(commands) {
          var fields = SOURCE_FIELDS.slice();
          (commands || []).filter(function(command) {
            return command && command.kind === "preset";
          }).forEach(function(command) {
            fields = fields.concat(command.brightnessFields || [], (command.observations || []).map(function(entry) {
              return entry.fieldId;
            }));
          });
          return Array.from(new Set(fields)).filter(function(id) {
            return typeof id === "string" && /^[a-z][A-Za-z0-9]*(\.[a-z][A-Za-z0-9]*)+$/.test(id);
          }).slice(0, 192);
        }
        var api = Object.freeze({ groups, numberValue, brightnessLabel: brightnessLabel2, readbackFields });
        if (typeof module === "object" && module.exports) module.exports = api;
        root.FlightFabricPresets = api;
      })(typeof globalThis !== "undefined" ? globalThis : window);
    }
  });

  // frontend/src/aircraft/toolbar-presets.js
  var toolbar_presets_exports = {};
  __export(toolbar_presets_exports, {
    createPresetPanel: () => createPresetPanel
  });

  // frontend/src/aircraft/fresh-aircraft-value.js
  function freshAircraftValue(state, fieldId, now = Date.now()) {
    var _a, _b, _c, _d;
    if ((state == null ? void 0 : state.sourceStatus) !== "connected" || ((_a = state == null ? void 0 : state.unavailable) == null ? void 0 : _a.includes(fieldId))) return null;
    const sampled = Date.parse((_b = state.valueUpdatedAt) == null ? void 0 : _b[fieldId]);
    const published = Date.parse(state.updatedAt);
    const elapsed = now - state.receivedAt;
    const age = now - sampled;
    if (!Number.isFinite(age) || !Number.isFinite(state.receivedAt) || elapsed < 0 || elapsed > 2e3 || !Number.isFinite(published) || now - published > 2e3 || now - published < -1e3 || sampled > published + 1e3 || age < -1e3 || age > 2e3) return null;
    return (_d = (_c = state.values) == null ? void 0 : _c[fieldId]) != null ? _d : null;
  }

  // frontend/src/aircraft/preset-observation.js
  var PAIRED_PRESET_FIELDS = Object.freeze({
    "flightGuidance.course.setBoth": {
      fields: ["mcp.courseCaptainDeg", "mcp.courseFirstOfficerDeg"],
      reason: "Waiting for live course-window readings."
    },
    "radios.nav.setBothActive": {
      fields: ["radios.nav1ActiveMhz", "radios.nav2ActiveMhz"],
      reason: "Waiting for live NAV frequency readings."
    }
  });
  function presetSourceUnavailableReason(command, snapshot, catalogue, now = Date.now()) {
    var _a;
    const templateId = (snapshot == null ? void 0 : snapshot.templateId) || (catalogue == null ? void 0 : catalogue.configurationId);
    const lightPreset = String((command == null ? void 0 : command.id) || "").startsWith("configuration.lights.");
    if ((catalogue == null ? void 0 : catalogue.configurationId) && catalogue.configurationId !== "generic" && (lightPreset || (command == null ? void 0 : command.id) === "configuration.apu.start")) {
      if ((snapshot == null ? void 0 : snapshot.activeProfileKey) !== catalogue.profileKey || (snapshot == null ? void 0 : snapshot.activeProfileRevision) !== catalogue.profileRevision)
        return "Waiting for live aircraft data.";
      if ((snapshot == null ? void 0 : snapshot.sourceStatus) !== "connected") return ["pmdg-737", "pmdg-777"].includes(templateId) ? "Waiting for live PMDG SDK data." : "Waiting for live aircraft data.";
    }
    if (templateId === "tfdi-md-11" && lightPreset) {
      if ((snapshot == null ? void 0 : snapshot.sourceStatus) !== "connected" || snapshot.activeProfileKey !== (catalogue == null ? void 0 : catalogue.profileKey) || snapshot.activeProfileRevision !== (catalogue == null ? void 0 : catalogue.profileRevision)) return "Waiting for live aircraft data.";
      const power = freshAircraftValue(snapshot, "systems.busVoltage", now);
      if (typeof power !== "number" || !Number.isFinite(power) || power < 90 || power > 130) return "Fresh aircraft electrical power required.";
      const selectors = ["lights.landingLeftPosition", "lights.landingRightPosition", "lights.nosePosition"];
      const switches = ["lights.turnoffLeft", "lights.turnoffRight", "lights.strobe", "lights.nav"];
      return selectors.some((id) => ![0, 1, 2].includes(freshAircraftValue(snapshot, id, now))) || switches.some((id) => typeof freshAircraftValue(snapshot, id, now) !== "boolean") ? "Waiting for live exterior light readings." : "";
    }
    if (["inibuilds-a350", "inibuilds-a380"].includes(templateId) && lightPreset) {
      if ((snapshot == null ? void 0 : snapshot.sourceStatus) !== "connected" || snapshot.activeProfileKey !== (catalogue == null ? void 0 : catalogue.profileKey) || snapshot.activeProfileRevision !== (catalogue == null ? void 0 : catalogue.profileRevision)) return "Waiting for live aircraft data.";
      return ["lights.landing", "lights.noseMode", "lights.strobeMode", templateId === "inibuilds-a380" ? "lights.nav" : "lights.navMode"].some((id) => freshAircraftValue(snapshot, id, now) === null) ? "Waiting for live exterior light readings." : "";
    }
    if (templateId === "inibuilds-a380" && command.id === "configuration.apu.start") {
      if ((snapshot == null ? void 0 : snapshot.sourceStatus) !== "connected" || snapshot.activeProfileKey !== (catalogue == null ? void 0 : catalogue.profileKey) || snapshot.activeProfileRevision !== (catalogue == null ? void 0 : catalogue.profileRevision)) return "Waiting for live aircraft data.";
      return ["systems.apuMaster", "systems.apuStart", "systems.apuAvailable", "systems.apuMasterFault"].some((id) => freshAircraftValue(snapshot, id, now) === null) ? "Waiting for live APU readings." : "";
    }
    const paired = PAIRED_PRESET_FIELDS[command.id];
    if (templateId === "pmdg-737" && paired) {
      if ((snapshot == null ? void 0 : snapshot.sourceStatus) !== "connected" || snapshot.activeProfileKey !== (catalogue == null ? void 0 : catalogue.profileKey) || snapshot.activeProfileRevision !== (catalogue == null ? void 0 : catalogue.profileRevision)) return "Waiting for live aircraft data.";
      return paired.fields.some((id) => {
        var _a2;
        return ((_a2 = snapshot.unavailable) == null ? void 0 : _a2.includes(id)) || !Object.prototype.hasOwnProperty.call(snapshot.values || {}, id);
      }) ? paired.reason : "";
    }
    if (!["pmdg-737", "pmdg-777"].includes(templateId) || !(lightPreset || command.id === "configuration.apu.start")) return "";
    const sdkStatus = ((_a = snapshot == null ? void 0 : snapshot.sourceStatuses) == null ? void 0 : _a.sdk) || (snapshot == null ? void 0 : snapshot.sourceStatus);
    return (snapshot == null ? void 0 : snapshot.sourceStatus) !== "connected" || sdkStatus !== "connected" ? "Waiting for live PMDG SDK data." : "";
  }
  function presetObservation(command, snapshot, nowMs = Date.now()) {
    var _a;
    if ((snapshot == null ? void 0 : snapshot.available) !== true) return null;
    const matches = ((_a = command == null ? void 0 : command.observations) == null ? void 0 : _a.filter((observation) => Object.is(freshAircraftValue(snapshot, observation.fieldId, nowMs), observation.expectedValue))) || [];
    if (!matches.length) return null;
    return __spreadProps(__spreadValues({}, matches[0]), { inhibitsRequest: matches.some((observation) => observation.inhibitsRequest === true) });
  }

  // frontend/src/aircraft/preset-presentation.js
  var import_aircraft_presets = __toESM(require_aircraft_presets(), 1);
  var { groups: presetGroups, numberValue: presetNumberValue, brightnessLabel } = (typeof globalThis !== "undefined" ? globalThis : window).FlightFabricPresets;

  // frontend/src/aircraft/toolbar-presets.js
  function createPresetPanel({ document, send, setTimeout, clearTimeout, now = Date.now }) {
    const element = node("section", "card presets-section");
    element.setAttribute("aria-label", "Presets");
    element.id = "toolbar-presets";
    element.hidden = true;
    let context = "", catalogue = {}, snapshot = null, connection = {}, rows = [], pending = null;
    let tick = null, sequence = 0, signature = "", enabled = false;
    const drafts = /* @__PURE__ */ Object.create(null), feedback = /* @__PURE__ */ Object.create(null);
    function node(tag, className, text) {
      const result = document.createElement(tag);
      result.className = className || "";
      if (text !== void 0) result.textContent = text;
      return result;
    }
    function clear(target) {
      while (target.firstChild) target.removeChild(target.firstChild);
    }
    function contextKey(value) {
      return value.profileKey + ":" + value.profileRevision;
    }
    function currentSnapshot(message) {
      return message && message.profileKey === catalogue.profileKey && message.profileRevision === catalogue.profileRevision;
    }
    function reset() {
      snapshot = null;
      pending = null;
      Object.keys(drafts).forEach((key) => delete drafts[key]);
      Object.keys(feedback).forEach((key) => delete feedback[key]);
    }
    function loseConnection() {
      snapshot = null;
      if (pending) feedback[pending.id] = { text: "Connection lost. Outcome unknown; check the cockpit before applying again.", tone: "warn" };
      pending = null;
    }
    function statusReason(command) {
      if (!connection.connected) return "Waiting for FlightFabric.";
      if (connection.scope !== "toolbar-presets" && connection.scope !== "full-control" && connection.scope !== "aircraft-control") return "Preset access is unavailable. Reopen the panel after updating FlightFabric.";
      const sim = connection.simState;
      if (!sim || sim.simconnectConnected !== true) return "Waiting for the simulator connection.";
      if (sim.inMenu || ["crashed", "loading", "shutting_down", "shutting-down"].includes(sim.lifecycleState)) return "Presets are unavailable while the simulator is loading or in a menu.";
      if (catalogue.configurationId !== "generic" && (!snapshot || !snapshot.available || snapshot.sourceStatus !== "connected" || now() - snapshot.receivedAt > 2e3 || now() - Date.parse(snapshot.updatedAt) > 2e3 || !Number.isFinite(Date.parse(snapshot.updatedAt)) || Date.parse(snapshot.updatedAt) > now() + 1e3)) return "Waiting for live aircraft data.";
      if (pending) return "A preset is being applied.";
      const sourceReason = presetSourceUnavailableReason(command, snapshot, catalogue, now());
      if (sourceReason) return sourceReason;
      const observed = presetObservation(command, snapshot, now());
      if (observed && observed.inhibitsRequest) return observed.label;
      if (command.brightnessFields && !brightnessValues(command)) return "Waiting for live dimmer readings.";
      if (command.input.kind === "number" && presetNumberValue(command, drafts[command.id]) === null) {
        return "Enter a value from " + command.input.min + " to " + command.input.max + " in steps of " + command.input.step + ".";
      }
      return "";
    }
    function brightnessValues(command) {
      if (!snapshot || !command.brightnessFields || !command.brightnessFields.length) return null;
      const values = command.brightnessFields.map((id) => freshAircraftValue(snapshot, id, now()));
      return values.every((value) => typeof value === "number" && Number.isFinite(value) && value >= 0 && value <= 100) ? values : null;
    }
    function apply(command) {
      if (!enabled || statusReason(command)) return false;
      const requestId = "toolbar-preset-" + now() + "-" + ++sequence;
      pending = { id: command.id, requestId, context, at: now() };
      delete feedback[command.id];
      refresh();
      const input = command.input.kind === "number" ? { value: presetNumberValue(command, drafts[command.id]) } : {};
      if (!send({
        type: "executeAircraftCommand",
        commandId: command.id,
        input,
        profileKey: catalogue.profileKey,
        profileRevision: catalogue.profileRevision,
        requestId
      })) {
        loseConnection();
        refresh();
        return false;
      }
      return true;
    }
    function row(command, parent, brightness) {
      const item = node("form", "preset-row" + (brightness ? " preset-brightness" : ""));
      item.setAttribute("data-preset", command.id);
      item.appendChild(node("h4", "preset-label", brightness ? brightnessLabel(command.id) : command.label));
      item.appendChild(node("p", "preset-description", command.description));
      const observed = node("p", "preset-observed muted");
      item.appendChild(observed);
      const phrase = command.speech && (command.speech.example || (command.speech.patterns || []).find((value) => !value.includes("{value}")));
      if (phrase) item.appendChild(node("p", "preset-voice muted", 'Say "' + phrase + '"'));
      const actions = node("div", "preset-actions");
      let input = null, range = null, target = null;
      if (command.input.kind === "number") {
        if (brightness && drafts[command.id] === void 0) drafts[command.id] = command.id.endsWith(".cockpit") ? "50" : "75";
        if (brightness) {
          target = node("label", "preset-target");
          target.htmlFor = "preset-range-" + command.id;
          item.appendChild(target);
          range = node("input", "preset-range");
          range.type = "range";
          range.id = target.htmlFor;
          range.min = command.input.min;
          range.max = command.input.max;
          range.step = command.input.step;
          range.value = drafts[command.id] || "0";
          range.setAttribute("aria-label", brightnessLabel(command.id) + " target percentage");
          range.addEventListener("input", () => {
            drafts[command.id] = range.value;
            input.value = range.value;
            refresh();
          });
          item.appendChild(range);
        }
        input = node("input", "preset-value");
        input.type = "number";
        input.inputMode = "decimal";
        input.min = command.input.min;
        input.max = command.input.max;
        input.step = command.input.step;
        input.value = drafts[command.id] || "";
        input.placeholder = command.id === "flightGuidance.course.setBoth" ? "270" : command.id === "radios.nav.setBothActive" ? "110.30" : String(command.input.min);
        input.setAttribute("aria-label", (brightness ? brightnessLabel(command.id) : command.label) + " value");
        input.addEventListener("input", () => {
          drafts[command.id] = input.value;
          if (range) range.value = input.value;
          refresh();
        });
        actions.appendChild(input);
        const units = { degrees: "deg", megahertz: "MHz", percent: "%", feet: "ft", knots: "kt" };
        if (units[command.input.units]) actions.appendChild(node("span", "muted", units[command.input.units]));
      }
      const button = node("button", "preset-apply");
      button.type = "submit";
      button.setAttribute("aria-label", (brightness ? "Set " : "Apply ") + (brightness ? brightnessLabel(command.id) : command.label));
      actions.appendChild(button);
      item.appendChild(actions);
      const reason = node("p", "preset-reason warn");
      reason.id = "preset-reason-" + command.id;
      button.setAttribute("aria-describedby", reason.id);
      item.appendChild(reason);
      const result = node("p", "preset-result");
      result.setAttribute("role", "status");
      result.setAttribute("aria-live", "polite");
      item.appendChild(result);
      item.addEventListener("submit", (event) => {
        event.preventDefault();
        apply(command);
      });
      parent.appendChild(item);
      rows.push({ command, item, observed, button, input, range, target, reason, result });
    }
    function render() {
      const active = document.activeElement;
      if (active && typeof element.contains === "function" && element.contains(active) && typeof active.blur === "function") active.blur();
      clear(element);
      rows = [];
      const art = node("img", "preset-watermark");
      art.src = "/assets/aircraft-presets.svg";
      art.alt = "";
      art.setAttribute("aria-hidden", "true");
      element.appendChild(art);
      const heading = node("div", "preset-heading");
      const icon = document.createElementNS("http://www.w3.org/2000/svg", "svg");
      icon.setAttribute("viewBox", "0 0 24 24");
      icon.setAttribute("aria-hidden", "true");
      icon.setAttribute("focusable", "false");
      const path = document.createElementNS("http://www.w3.org/2000/svg", "path");
      path.setAttribute("d", "m12 3 9 5-9 5-9-5 9-5Z M3 12l9 5 9-5M3 16l9 5 9-5");
      icon.appendChild(path);
      heading.appendChild(icon);
      const title = node("div");
      title.appendChild(node("h3", "", "Presets"));
      title.appendChild(node("p", "muted", "Apply a group of settings together."));
      heading.appendChild(title);
      element.appendChild(heading);
      const groups = presetGroups(catalogue.commands);
      groups.cards.forEach((command) => row(command, element, false));
      if (groups.lights.length) {
        const lights = node("div", "preset-group");
        lights.appendChild(node("h3", "", "Exterior lights"));
        lights.appendChild(node("p", "muted", "Reviewed light configurations by flight phase."));
        groups.lights.forEach((command) => row(command, lights, false));
        element.appendChild(lights);
      }
      groups.brightness.forEach((command) => row(command, element, true));
      element.hidden = rows.length === 0;
      refresh();
    }
    function refresh() {
      if (pending && now() - pending.at > 12e4) {
        feedback[pending.id] = { text: "No result received. Check the cockpit before applying again.", tone: "warn" };
        pending = null;
      }
      rows.forEach(({ command, button, input, range, target, reason, result, observed }) => {
        const why = statusReason(command), busy = pending && pending.id === command.id;
        button.disabled = !enabled || Boolean(why);
        button.textContent = busy ? command.id === "configuration.apu.start" ? "Requesting..." : "Applying..." : command.id === "configuration.apu.start" ? "Start" : range ? "Set" : input ? "Set both" : "Apply";
        if (input) input.disabled = Boolean(pending);
        if (range) range.disabled = Boolean(pending);
        if (target) target.textContent = "Target brightness: " + (presetNumberValue(command, drafts[command.id]) === null ? "--" : drafts[command.id]) + "%";
        reason.textContent = why;
        reason.hidden = !why || input && !range && !String(drafts[command.id] || "").trim() && why.startsWith("Enter a value");
        const entry = feedback[command.id];
        result.textContent = entry ? entry.text : "";
        result.className = "preset-result " + (entry ? entry.tone : "");
        result.hidden = !entry;
        let observation = "";
        if (range) {
          const values = brightnessValues(command);
          observation = "Observed: " + (!values ? "Unavailable" : values.every((value) => value === values[0]) ? values[0] + "%" : "Mixed");
        } else if (command.id === "configuration.apu.start") {
          const value = presetObservation(command, snapshot, now());
          observation = value ? value.label : "APU status unknown";
        }
        observed.textContent = observation;
        observed.hidden = !observation;
      });
    }
    function schedule() {
      if (tick !== null) clearTimeout(tick);
      tick = enabled && connection.connected && rows.length ? setTimeout(() => {
        tick = null;
        refresh();
        schedule();
      }, 500) : null;
    }
    function update(next) {
      connection = next;
      const nextCatalogue = next.profile && next.profile.controlCapabilities && next.profile.controlCapabilities.aircraftCommands || {};
      const nextContext = contextKey(nextCatalogue);
      if (context !== nextContext) {
        reset();
        context = nextContext;
      }
      catalogue = nextCatalogue;
      const nextSignature = JSON.stringify(catalogue);
      enabled = next.visible === true;
      if (!next.connected) loseConnection();
      if (next.simState && (next.simState.simconnectConnected !== true || next.simState.inMenu === true)) snapshot = null;
      if (enabled) {
        if (signature !== nextSignature) {
          signature = nextSignature;
          render();
        } else refresh();
      }
      schedule();
    }
    function receive(message) {
      if (message.type === "toolbarPresetState" && currentSnapshot(message)) {
        snapshot = Object.assign({}, message, {
          receivedAt: now(),
          activeProfileKey: message.profileKey,
          activeProfileRevision: message.profileRevision,
          sourceStatus: message.sourceStatus && (message.sourceStatus.overall || message.sourceStatus.lvar),
          sourceStatuses: message.sourceStatus && (message.sourceStatus.sources || { lvar: message.sourceStatus.lvar })
        });
        if (enabled) refresh();
      }
      if (message.type === "aircraftCommandResult" && pending && message.requestId === pending.requestId && pending.context === context) {
        const partial = Number(message.completedStepCount) > 0 || message.executionStarted === true;
        const text = message.ok ? message.code === "sent_unconfirmed" ? "Request sent. Check the cockpit; the setting is not confirmed." : "Preset applied." : partial ? "Preset stopped after some changes" + (message.failedStepLabel ? " at " + message.failedStepLabel : "") + ". Check the cockpit before trying again." : "Preset could not be applied" + (message.failedStepLabel ? " at " + message.failedStepLabel : "") + ". Check aircraft readiness and try again.";
        feedback[pending.id] = { text, tone: message.ok && message.code !== "sent_unconfirmed" ? "good" : "warn" };
        pending = null;
        if (enabled) refresh();
      }
    }
    return {
      element,
      update,
      receive,
      reset: () => {
        reset();
        signature = "";
      },
      destroy: () => {
        enabled = false;
        loseConnection();
        if (tick !== null) clearTimeout(tick);
        tick = null;
      }
    };
  }
  return __toCommonJS(toolbar_presets_exports);
})();
