// Generated by scripts/build-toolbar-presets.mjs. Do not edit.
var FlightFabricToolbarTaxi = (() => {
  var __defProp = Object.defineProperty;
  var __defProps = Object.defineProperties;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropDescs = Object.getOwnPropertyDescriptors;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __getOwnPropSymbols = Object.getOwnPropertySymbols;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __propIsEnum = Object.prototype.propertyIsEnumerable;
  var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
  var __spreadValues = (a, b) => {
    for (var prop in b || (b = {}))
      if (__hasOwnProp.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    if (__getOwnPropSymbols)
      for (var prop of __getOwnPropSymbols(b)) {
        if (__propIsEnum.call(b, prop))
          __defNormalProp(a, prop, b[prop]);
      }
    return a;
  };
  var __spreadProps = (a, b) => __defProps(a, __getOwnPropDescs(b));
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // frontend/src/aircraft/toolbar-taxi.js
  var toolbar_taxi_exports = {};
  __export(toolbar_taxi_exports, {
    createTaxiPanel: () => createTaxiPanel
  });

  // frontend/src/aircraft/autotaxi-chase-view.js
  var DEG = Math.PI / 180;
  var MARGIN = 40;
  function createChaseCamera({ w = 360, h = 300, hfovDeg = 60, pitchDeg = 14, backM = 72, upM = 40, nearM = 2, farM = 1600 } = {}) {
    const F = w / 2 / Math.tan(hfovDeg / 2 * DEG);
    const sin = Math.sin(pitchDeg * DEG), cos = Math.cos(pitchDeg * DEG);
    const cx = w / 2, cy = h / 2;
    const toCamera = (r, u, f) => ({ x: r, y: (u - upM) * cos + (f + backM) * sin, d: (f + backM) * cos - (u - upM) * sin });
    const toScreen = (c) => [cx + F * c.x / c.d, cy - F * c.y / c.d];
    const kx = (w / 2 + MARGIN) / F, ky = (h + MARGIN - cy) / F;
    const planes = [(p) => p.d - nearM, (p) => p.x + kx * p.d, (p) => -p.x + kx * p.d, (p) => p.y + ky * p.d];
    return { w, h, F, cx, cy, horizonY: cy - F * sin / cos, nearM, farM, backM, upM, toCamera, toScreen, planes };
  }
  function aircraftFrame({ x, z, headingDeg }) {
    const s = Math.sin(headingDeg * DEG), c = Math.cos(headingDeg * DEG);
    return (p) => ({ r: (p.x - x) * c - (p.z - z) * s, f: (p.x - x) * s + (p.z - z) * c });
  }
  function clip(points, inside) {
    const out = [];
    for (let i = 0; i < points.length; i++) {
      const a = points[i], b = points[(i + 1) % points.length], da = inside(a), db = inside(b);
      if (da >= 0) out.push(a);
      if (da >= 0 !== db >= 0) {
        const t = da / (da - db);
        out.push({ x: a.x + t * (b.x - a.x), y: a.y + t * (b.y - a.y), d: a.d + t * (b.d - a.d) });
      }
    }
    return out;
  }
  var fmt = ([x, y]) => `${x.toFixed(1)},${y.toFixed(1)}`;
  function cameraPath(cam, points) {
    if (points.every((p) => p.d > cam.farM)) return null;
    const clipped = cam.planes.reduce(clip, points);
    return clipped.length < 3 ? null : `M${clipped.map((p) => fmt(cam.toScreen(p))).join("L")}Z`;
  }
  var groundPath = (cam, frame, points) => cameraPath(cam, points.map((p) => {
    const l = frame(p);
    return cam.toCamera(l.r, 0, l.f);
  }));
  function groundSegment(cam, frame, from, to) {
    let [a, b] = [from, to].map((p) => {
      const l = frame(p);
      return cam.toCamera(l.r, 0, l.f);
    });
    if (a.d > cam.farM && b.d > cam.farM) return null;
    for (const inside of cam.planes) {
      const da = inside(a), db = inside(b);
      if (da < 0 && db < 0) return null;
      if (da < 0 || db < 0) {
        const t = da / (da - db), m = { x: a.x + t * (b.x - a.x), y: a.y + t * (b.y - a.y), d: a.d + t * (b.d - a.d) };
        if (da < 0) a = m;
        else b = m;
      }
    }
    return `M${fmt(cam.toScreen(a))}L${fmt(cam.toScreen(b))}`;
  }
  function label(cam, frame, p, text, basePx) {
    const l = frame(p), c = cam.toCamera(l.r, 0, l.f);
    if (c.d < cam.nearM) return null;
    const size = Math.min(basePx, basePx * cam.F / c.d);
    if (size < 6) return null;
    const [x, y] = cam.toScreen(c);
    if (x < -20 || x > cam.w + 20 || y > cam.h + 20) return null;
    return { text, x: Math.round(x), y: Math.round(y), size: Math.round(size * 10) / 10 };
  }
  function quad(a, b, half, capM = 0) {
    const len = Math.hypot(b.x - a.x, b.z - a.z) || 1;
    const ux = (b.x - a.x) / len, uz = (b.z - a.z) / len, nx = -uz * half, nz = ux * half;
    const p = { x: a.x - ux * capM, z: a.z - uz * capM }, q = { x: b.x + ux * capM, z: b.z + uz * capM };
    return [{ x: p.x + nx, z: p.z + nz }, { x: q.x + nx, z: q.z + nz }, { x: q.x - nx, z: q.z - nz }, { x: p.x - nx, z: p.z - nz }];
  }
  function disc(c, r, n = 12) {
    return Array.from({ length: n }, (_, i) => ({ x: c.x + r * Math.sin(i / n * 2 * Math.PI), z: c.z + r * Math.cos(i / n * 2 * Math.PI) }));
  }
  function dashes(from, to, dashM, gapM, half) {
    const len = Math.hypot(to.x - from.x, to.z - from.z), ux = (to.x - from.x) / (len || 1), uz = (to.z - from.z) / (len || 1);
    const out = [];
    for (let s = 0; s < len; s += dashM + gapM) {
      const e = Math.min(len, s + dashM);
      out.push(quad({ x: from.x + ux * s, z: from.z + uz * s }, { x: from.x + ux * e, z: from.z + uz * e }, half));
    }
    return out;
  }
  function smoothRoute(points, radiusM = 25) {
    if (!Array.isArray(points) || points.length < 3) return points;
    const out = [points[0]];
    for (let i = 1; i < points.length - 1; i++) {
      const a = points[i - 1], p = points[i], b = points[i + 1];
      const inLen = Math.hypot(p.x - a.x, p.z - a.z), outLen = Math.hypot(b.x - p.x, b.z - p.z);
      if (!inLen || !outLen) {
        out.push(p);
        continue;
      }
      const ux = (p.x - a.x) / inLen, uz = (p.z - a.z) / inLen, vx = (b.x - p.x) / outLen, vz = (b.z - p.z) / outLen;
      const turn = Math.acos(Math.max(-1, Math.min(1, ux * vx + uz * vz)));
      if (turn < 3 * DEG) {
        out.push(p);
        continue;
      }
      const t = Math.min(radiusM * Math.tan(turn / 2), 24 / Math.sin(turn / 2), inLen * 0.45, outLen * 0.45);
      const start = { x: p.x - ux * t, z: p.z - uz * t }, end = { x: p.x + vx * t, z: p.z + vz * t };
      const steps = Math.max(2, Math.ceil(turn / (10 * DEG)));
      for (let k = 0; k <= steps; k++) {
        const s = k / steps, w0 = (1 - s) ** 2, w1 = 2 * (1 - s) * s, w2 = s * s;
        out.push({ x: w0 * start.x + w1 * p.x + w2 * end.x, z: w0 * start.z + w1 * p.z + w2 * end.z });
      }
    }
    out.push(points[points.length - 1]);
    return out;
  }
  function projectTaxiScene(cam, { scene, route, aircraft, done = [], ahead = route.points }) {
    const frame = aircraftFrame(aircraft);
    const ground = (points) => groundPath(cam, frame, points);
    const join = (paths) => paths.filter(Boolean).join("");
    const ribbon = (points, half) => join([...points.slice(1).map((p, i) => ground(quad(points[i], p, half))), ...points.map((p) => ground(disc(p, half)))]);
    const pavement = { taxi: [], runway: [] }, centrelines = { taxi: [], runway: [] }, edges = { taxi: [], runway: [] };
    const toCamera = (p) => {
      const l = frame(p);
      return cam.toCamera(l.r, 0, l.f);
    };
    for (const l of (scene == null ? void 0 : scene.links) || []) {
      const a = toCamera(l.a), b = toCamera(l.b);
      if (a.d > cam.farM && b.d > cam.farM || cam.planes.some((inside) => inside(a) < -l.widthM && inside(b) < -l.widthM)) continue;
      const kind = l.runway ? "runway" : "taxi";
      const slab = ground(quad(l.a, l.b, l.widthM / 2, l.widthM / 2));
      if (!slab) continue;
      pavement[kind].push(slab);
      centrelines[kind].push(groundSegment(cam, frame, l.a, l.b));
      const rim = quad(l.a, l.b, l.widthM / 2 + 0.6);
      edges[kind].push(groundSegment(cam, frame, rim[0], rim[1]), groundSegment(cam, frame, rim[3], rim[2]));
    }
    const runways = ((scene == null ? void 0 : scene.runways) || []).map((rw) => ({
      id: rw.id,
      reciprocal: rw.reciprocal,
      slab: ground(rw.corners),
      // ICAO centreline stripes: 30 m on, 20 m off, 0.9 m wide.
      dashes: join(dashes(rw.ends[0], rw.ends[1], 30, 20, 0.45).map(ground)),
      labels: rw.ends.map((end, i) => label(cam, frame, end, i ? rw.reciprocal : rw.id, 11)).filter(Boolean)
    })).filter((rw) => rw.slab);
    const stands = ((scene == null ? void 0 : scene.stands) || []).map((st) => ({ d: ground(disc(st, st.radiusM, 16)), label: label(cam, frame, st, st.label, 9) })).filter((st) => st.d);
    let hold = null;
    if (route.kind !== "stand") {
      const from = route.points[route.points.length - 1], to = route.holdShort;
      const len = Math.hypot(to.x - from.x, to.z - from.z) || 1;
      const ux = (to.x - from.x) / len, uz = (to.z - from.z) / len, nx = -uz, nz = ux;
      hold = {
        dash: join(dashes(from, to, 4, 4, 0.7).map(ground)),
        bar: ground([
          { x: to.x + nx * 14 + ux * 1.5, z: to.z + nz * 14 + uz * 1.5 },
          { x: to.x - nx * 14 + ux * 1.5, z: to.z - nz * 14 + uz * 1.5 },
          { x: to.x - nx * 14 - ux * 1.5, z: to.z - nz * 14 - uz * 1.5 },
          { x: to.x + nx * 14 - ux * 1.5, z: to.z + nz * 14 - uz * 1.5 }
        ])
      };
    }
    return {
      pavement: { taxi: join(pavement.taxi), runway: join(pavement.runway) },
      centrelines: { taxi: join(centrelines.taxi), runway: join(centrelines.runway) },
      edges: { taxi: join(edges.taxi), runway: join(edges.runway) },
      runways,
      stands,
      destinationStand: route.stand ? ground(disc(route.stand, route.stand.radiusM, 16)) : null,
      route: { done: ribbon(done, 3.5), glow: ribbon(ahead, 5), ahead: ribbon(ahead, 1.8) },
      hold,
      stop: ground(disc(route.points[route.points.length - 1], 2.2, 10))
    };
  }
  var FUSELAGE = [
    { f: 19, w: 0.15, b: 2.9, t: 3.1 },
    { f: 17.5, w: 0.9, b: 2.2, t: 3.9 },
    { f: 15, w: 1.5, b: 1.5, t: 4.6 },
    { f: 11, w: 1.85, b: 1.2, t: 5 },
    { f: -8, w: 1.9, b: 1.2, t: 5 },
    { f: -12, w: 1.7, b: 1.6, t: 5 },
    { f: -16, w: 1.1, b: 3, t: 4.9 },
    { f: -19, w: 0.4, b: 4, t: 4.6 }
  ];
  var ENGINE = [{ f: 5.5, w: 1.3, b: 0.5, t: 3.1 }, { f: 0, w: 1.2, b: 0.6, t: 3 }];
  var WING = [[2.2, 1.8, 3], [17.5, 3.6, -6], [17.5, 3.6, -9], [2.2, 1.8, -5]];
  var WINGLET = [[17.5, 3.6, -6], [17.5, 3.6, -9], [18.3, 6.2, -9.6], [18.3, 6.2, -7.6]];
  var STABILISER = [[0.4, 4.6, -13], [7, 4.9, -17], [7, 4.9, -19], [0.4, 4.6, -17.4]];
  var FIN = (sign) => [[sign * 0.4, 4.8, -10], [sign * 0.15, 11.5, -17.5], [sign * 0.15, 11.5, -19.8], [sign * 0.4, 4.6, -19]];
  var FIN_EDGE = [[0.4, 4.6, -19], [0.15, 11.5, -19.8], [-0.15, 11.5, -19.8], [-0.4, 4.6, -19]];
  var WINDSCREEN = [[-1.1, 4.25, 15.3], [1.1, 4.25, 15.3], [0.75, 3.95, 17], [-0.75, 3.95, 17]];
  var SILHOUETTE = [
    [0, 19],
    [2.2, 14],
    [2.2, 3],
    [17.5, -6],
    [17.5, -9],
    [2.2, -5],
    [2.2, -13],
    [7, -17],
    [7, -19],
    [0, -17.4],
    [-7, -19],
    [-7, -17],
    [-2.2, -13],
    [-2.2, -5],
    [-17.5, -9],
    [-17.5, -6],
    [-2.2, 3],
    [-2.2, 14]
  ];
  var LIGHT = [-0.3, 0.9, 0.35];
  var DARK = "#1b222c";
  var sub = (a, b) => [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
  var dot = (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
  var cross = (a, b) => [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]];
  var unit = (v) => {
    const l = Math.hypot(...v) || 1;
    return v.map((c) => c / l);
  };
  var centroid = (pts) => pts.reduce((s, p) => [s[0] + p[0] / pts.length, s[1] + p[1] / pts.length, s[2] + p[2] / pts.length], [0, 0, 0]);
  var normal = (pts) => unit(cross(sub(pts[1], pts[0]), sub(pts[2], pts[0])));
  var mirror = (pts) => pts.map(([r, u, f]) => [-r, u, f]).reverse();
  function ring({ f, w, b, t }, rOffset, sides) {
    const m = (b + t) / 2, v = (t - b) / 2;
    return Array.from({ length: sides }, (_, k) => {
      const a = k / sides * 2 * Math.PI;
      return [rOffset + w * Math.cos(a), m + v * Math.sin(a), f];
    });
  }
  function loft(stations, rOffset = 0, sides = 8) {
    const rings = stations.map((st) => ring(st, rOffset, sides));
    const faces = [];
    for (let i = 0; i + 1 < rings.length; i++) for (let k = 0; k < sides; k++) {
      const pts = [rings[i][k], rings[i][(k + 1) % sides], rings[i + 1][(k + 1) % sides], rings[i + 1][k]];
      const c = centroid(pts), axis = [rOffset, (stations[i].b + stations[i].t + stations[i + 1].b + stations[i + 1].t) / 4, c[2]];
      let n = normal(pts);
      if (dot(n, sub(c, axis)) < 0) n = n.map((v) => -v);
      faces.push({ pts, n, solid: true });
    }
    return faces;
  }
  var cap = (station, rOffset) => ({ pts: ring(station, rOffset, 8), n: [0, 0, -1], solid: true, fill: DARK });
  function shade(n, toCam) {
    const l = unit(LIGHT), h = unit([l[0] + toCam[0], l[1] + toCam[1], l[2] + toCam[2]]);
    const k = 0.42 + 0.58 * Math.max(0, dot(n, l)) + 0.3 * Math.max(0, dot(n, h)) ** 24;
    return `rgb(${Math.min(255, Math.round(238 * k))},${Math.min(255, Math.round(243 * k))},${Math.min(255, Math.round(248 * k))})`;
  }
  function aircraftSprite(cam) {
    const camPos = [0, cam.upM, -cam.backM];
    const flat = (pts) => ({ pts, n: normal(pts), solid: false });
    const faces = [
      ...loft(FUSELAGE),
      cap(FUSELAGE[FUSELAGE.length - 1], 0),
      ...[].concat(...[5.5, -5.5].map((r) => [...loft(ENGINE, r), cap(ENGINE[ENGINE.length - 1], r)])),
      ...[WING, mirror(WING), WINGLET, mirror(WINGLET), STABILISER, mirror(STABILISER), FIN(1), FIN(-1), FIN_EDGE].map(flat),
      // Painted on the nose: nudged nearer so it sorts above the skin it sits on.
      __spreadProps(__spreadValues({}, flat(WINDSCREEN)), { fill: DARK, overlay: true })
    ];
    const visible = [];
    for (const face of faces) {
      const toCam = unit(sub(camPos, centroid(face.pts)));
      let n = face.n;
      if (dot(n, toCam) < 0) {
        if (face.solid) continue;
        n = n.map((v) => -v);
      }
      const pts = face.pts.map(([r, u, f]) => cam.toCamera(r, u, f));
      visible.push({
        depth: pts.reduce((s, p) => s + p.d, 0) / pts.length - (face.overlay ? 0.5 : 0),
        fill: face.fill || shade(n, toCam),
        d: `M${pts.map((p) => fmt(cam.toScreen(p))).join("L")}Z`
      });
    }
    visible.sort((a, b) => b.depth - a.depth);
    return {
      faces: visible.map(({ fill, d }) => ({ fill, d })),
      shadow: cameraPath(cam, SILHOUETTE.map(([r, f]) => cam.toCamera(r + 1.2, 0, f - 1))),
      halo: cameraPath(cam, disc({ x: 0, z: 0 }, 24, 24).map((p) => cam.toCamera(p.x, 0, p.z)))
    };
  }

  // frontend/src/aircraft/taxi-progress.js
  function splitRoute(points, a) {
    if (!a) return { done: [], ahead: points, distanceM: null };
    let best = { d: Infinity, i: 0, p: points[0] };
    for (let i = 0; i < points.length - 1; i++) {
      const p = points[i], q = points[i + 1];
      const l2 = (q.x - p.x) ** 2 + (q.z - p.z) ** 2;
      const t = l2 ? Math.max(0, Math.min(1, ((a.x - p.x) * (q.x - p.x) + (a.z - p.z) * (q.z - p.z)) / l2)) : 0;
      const point2 = { x: p.x + t * (q.x - p.x), z: p.z + t * (q.z - p.z) };
      const d = Math.hypot(a.x - point2.x, a.z - point2.z);
      if (d < best.d) best = { d, i, p: point2 };
    }
    if (best.d > 25) return { done: [], ahead: points, distanceM: best.d };
    return { done: [...points.slice(0, best.i + 1), best.p], ahead: [best.p, ...points.slice(best.i + 1)], distanceM: best.d };
  }

  // frontend/src/aircraft/departure-preview.js
  function createDeparturePreview({ send, changed, now = Date.now, setTimeout, clearTimeout }) {
    const prefix = "departure-" + now() + "-" + Math.random().toString(36).slice(2) + "-";
    let context = {}, key = "", revision = 0, sequence = 0, pending = null, timer = null;
    let data = null, error = "", lastReply = -Infinity, nextAt = 0, destroyed = false;
    const usable = () => context.connected && context.visible !== false && context.enabled !== false && context.profileKey && /^[A-Z0-9]{3,8}$/.test(context.icao) && /^(0?[1-9]|[12][0-9]|3[0-6])[LRC]?$/.test(context.runway);
    function publish() {
      changed({ data, error, loading: (pending == null ? void 0 : pending.operation) === "preview", fresh: Boolean(data == null ? void 0 : data.aircraft) && now() - lastReply < 2e3 });
    }
    function reset() {
      revision++;
      pending = null;
      data = null;
      error = "";
      lastReply = -Infinity;
      nextAt = now() + 400;
      publish();
    }
    function update(next) {
      context = __spreadProps(__spreadValues({}, next), { icao: String(next.icao || "").trim().toUpperCase(), runway: String(next.runway || "").trim().toUpperCase() });
      const nextKey = [context.profileKey, context.profileRevision, context.icao, context.runway, usable()].join(":");
      if (key !== nextKey) {
        key = nextKey;
        reset();
      }
      if (!usable()) {
        if (timer !== null) clearTimeout(timer);
        timer = null;
        return;
      }
      if (timer === null && !destroyed) timer = setTimeout(tick, 50);
    }
    function request(operation) {
      const at = now(), requestId = prefix + ++sequence;
      pending = { requestId, operation, revision, at };
      const sent = send({
        type: "requestTaxiGuidance",
        operation,
        pushback: true,
        requestId,
        icao: context.icao,
        runway: context.runway,
        profileKey: context.profileKey,
        profileRevision: context.profileRevision,
        scene: !(data == null ? void 0 : data.scene)
      });
      if (sent === false) {
        pending = null;
        lastReply = -Infinity;
        error = "Taxi guidance connection lost.";
        nextAt = at + 1e3;
      }
      publish();
    }
    function tick() {
      timer = null;
      if (destroyed || !usable()) return;
      if (usable()) {
        if (pending && now() - pending.at > (pending.operation === "preview" ? 12e3 : 2e3)) {
          error = "Pushback preview unavailable. Retrying\u2026";
          pending = null;
          nextAt = now() + 3e3;
        }
        if (!pending && now() >= nextAt) request(!data || data.pushbackPreview.phase === "preview" && !data.pushbackPreview.valid ? "preview" : "status");
        publish();
      }
      timer = setTimeout(tick, 250);
    }
    function receive(message) {
      if (destroyed || !usable() || (message == null ? void 0 : message.type) !== "toolbarTaxiState" || !pending || pending.revision !== revision || pending.requestId !== message.requestId) return false;
      const requestedAt = pending.at;
      pending = null;
      if (message.ok !== true) {
        error = message.error || "Pushback preview unavailable.";
        lastReply = -Infinity;
        nextAt = now() + 5e3;
        publish();
        return true;
      }
      if (message.currentProfileKey !== context.profileKey || message.currentProfileRevision !== context.profileRevision) {
        reset();
        return true;
      }
      const preview = message.pushbackPreview;
      if (preview && preview.icao === context.icao && preview.runway.replace(/^0(?=\d)/, "") === context.runway.replace(/^0(?=\d)/, "")) {
        const previous = preview.id === (data == null ? void 0 : data.pushbackPreview.id) ? data : null;
        data = {
          pushbackPreview: __spreadValues(__spreadValues({}, previous == null ? void 0 : previous.pushbackPreview), preview),
          aircraft: message.aircraft,
          scene: message.scene || (previous == null ? void 0 : previous.scene) || null,
          route: message.preview || (previous == null ? void 0 : previous.route) || null
        };
        if (!data.pushbackPreview.points || !data.route) data = null;
      } else data = null;
      lastReply = requestedAt;
      error = "";
      nextAt = now() + (["connecting", "pushing", "stopping"].includes(preview == null ? void 0 : preview.phase) ? 250 : 750);
      publish();
      return true;
    }
    return { update, receive, reset, destroy() {
      destroyed = true;
      if (timer !== null) clearTimeout(timer);
      timer = null;
      reset();
    } };
  }

  // frontend/src/aircraft/pushback-map.js
  var plane = "M0,-12L3,-4L11,2L11,5L3,2L3,8L6,10L6,12L0,10L-6,12L-6,10L-3,8L-3,2L-11,5L-11,2L-3,-4Z";
  var point = (p) => p && [p.x, p.z].every(Number.isFinite);
  var views = /* @__PURE__ */ new WeakMap();
  var amber = "var(--taxi-pushback, #e8b35c)";
  var green = "var(--taxi-success, #34d399)";
  function pushbackCaption(data, fresh = true) {
    const p = data == null ? void 0 : data.pushbackPreview;
    if (!p) return "";
    const heading = String(Math.round(p.headingDeg) % 360).padStart(3, "0") + "\xB0";
    const stage = p.phase === "complete" ? "Pushback complete" : p.phase === "connecting" ? "Connecting tug" : p.phase === "stopping" ? "Stopping pushback" : p.phase === "pushing" ? "Pushback in progress" : "Pushback preview";
    const remaining = Math.round(Number.isFinite(p.remainingM) ? p.remainingM : p.lengthM);
    const detail = p.phase === "complete" ? " \xB7 Taxi to runway " + p.runway + "." : " \xB7 " + remaining + (p.phase === "preview" ? " m reverse" : " m remaining") + " \xB7 Finish facing " + heading + " \xB7 Then taxi to runway " + p.runway + ".";
    return (!fresh ? "Reference only \xB7 Live position unavailable. " : "") + stage + detail;
  }
  function renderPushbackMap(root, data, fresh = true) {
    var _a;
    root.setAttribute("viewBox", "0 0 360 300");
    root.setAttribute("role", "img");
    root.setAttribute("focusable", "false");
    root.setAttribute("aria-label", pushbackCaption(data, fresh));
    root.setAttribute("data-pushback-map", "");
    const preview = data == null ? void 0 : data.pushbackPreview, points = preview == null ? void 0 : preview.points;
    if (!Array.isArray(points) || points.length < 2 || !points.every(point) || !Number.isFinite(preview.headingDeg)) {
      while (root.firstChild) root.removeChild(root.firstChild);
      views.delete(root);
      return;
    }
    let view = views.get(root);
    if (!view || view.id !== preview.id || view.sceneKey !== ((_a = data.scene) == null ? void 0 : _a.key) || !root.contains(view.background)) {
      while (root.firstChild) root.removeChild(root.firstChild);
      view = buildMap(root, data);
      views.set(root, view);
    }
    const completed = preview.phase === "complete", color = completed ? green : amber;
    const aircraft = fresh && point(data.aircraft) && Number.isFinite(data.aircraft.headingDeg) ? data.aircraft : null;
    const progress = splitRoute(points, aircraft);
    view.ahead.setAttribute("points", view.coordinates(completed ? [] : progress.ahead));
    view.finish.setAttribute("stroke", color);
    view.title.setAttribute("fill", fresh ? color : "var(--taxi-aircraft, #e8eef5)");
    view.title.textContent = !fresh ? "Reference only" : completed ? "Pushback complete" : preview.phase === "connecting" ? "Connecting tug" : preview.phase === "pushing" ? "Pushing back" : preview.phase === "stopping" ? "Stopping\u2026" : "Pushback preview";
    const remaining = Number.isFinite(preview.remainingM) ? preview.remainingM : preview.lengthM;
    view.distance.textContent = !fresh ? "" : completed ? "Ready to taxi" : Math.round(remaining) + (preview.phase === "preview" ? " m reverse" : " m left");
    view.distance.setAttribute("fill", completed ? green : "var(--taxi-aircraft, #e8eef5)");
    const measured = fresh && Number.isFinite(remaining) && preview.lengthM > 0 && ["pushing", "stopping", "complete"].includes(preview.phase);
    const fraction = measured ? completed ? 1 : Math.max(0, Math.min(1, 1 - remaining / preview.lengthM)) : 0;
    view.track.setAttribute("opacity", measured ? 0.2 : 0);
    view.meter.setAttribute("opacity", measured ? 1 : 0);
    view.meter.setAttribute("stroke", color);
    view.meter.setAttribute("data-pushback-progress", measured ? Math.round(fraction * 100) : "");
    view.meter.setAttribute("style", "transition:stroke-dashoffset var(--taxi-motion-duration, 250ms) linear;stroke-dashoffset:" + 328 * (1 - fraction));
    if (aircraft) {
      const a = view.xy(aircraft), continuing = Boolean(view.aircraft);
      if (!continuing) view.aircraft = view.svg("path", {
        d: plane,
        fill: "var(--taxi-aircraft, #e8eef5)",
        stroke: "var(--taxi-ground, #141d28)",
        "stroke-width": 1,
        "data-pushback-aircraft": ""
      });
      view.heading = continuing ? view.heading + ((aircraft.headingDeg - view.heading + 540) % 360 + 360) % 360 - 180 : aircraft.headingDeg;
      view.aircraft.setAttribute("transform", "translate(" + a.join(",") + ") rotate(" + view.heading + ")");
      view.aircraft.setAttribute("style", "transition:transform " + (continuing ? "var(--taxi-motion-duration, 250ms)" : "0ms") + " linear;transform:translate(" + a[0] + "px," + a[1] + "px) rotate(" + view.heading + "deg)");
    } else if (view.aircraft) {
      root.removeChild(view.aircraft);
      view.aircraft = null;
    }
  }
  function buildMap(root, data) {
    var _a, _b, _c;
    const preview = data.pushbackPreview, points = preview.points;
    const finish = points[points.length - 1], taxi = (((_a = data.route) == null ? void 0 : _a.points) || []).filter(point);
    const onward = taxi.length ? [taxi[0]] : [];
    let length = 0;
    for (let i = 1; i < taxi.length && length < 55; i++) {
      const a = taxi[i - 1], b = taxi[i], segment = Math.hypot(b.x - a.x, b.z - a.z);
      const f = Math.min(1, (55 - length) / (segment || 1));
      onward.push({ x: a.x + (b.x - a.x) * f, z: a.z + (b.z - a.z) * f });
      length += segment;
    }
    const all = points.concat(onward), xs = all.map((p) => p.x), zs = all.map((p) => p.z);
    const minX = Math.min(...xs) - 16, maxX = Math.max(...xs) + 16, minZ = Math.min(...zs) - 16, maxZ = Math.max(...zs) + 16;
    const scale = Math.min(312 / Math.max(60, maxX - minX), 232 / Math.max(60, maxZ - minZ));
    const xy = (p) => [180 + (p.x - (minX + maxX) / 2) * scale, 150 - (p.z - (minZ + maxZ) / 2) * scale];
    const svg = (tag, attrs, text) => {
      const node = root.ownerDocument.createElementNS("http://www.w3.org/2000/svg", tag);
      Object.keys(attrs).forEach((key) => node.setAttribute(key, String(attrs[key])));
      if (text !== void 0) node.textContent = text;
      root.appendChild(node);
      return node;
    };
    const coordinates = (ps) => ps.map((p) => xy(p).join(",")).join(" ");
    const line = (ps, attrs) => svg("polyline", __spreadValues({
      points: coordinates(ps),
      fill: "none",
      "stroke-linecap": "round",
      "stroke-linejoin": "round"
    }, attrs));
    const background = svg("rect", { width: 360, height: 300, fill: "var(--taxi-ground, #141d28)" });
    for (const l of ((_b = data.scene) == null ? void 0 : _b.links) || []) {
      if (!point(l.a) || !point(l.b) || !Number.isFinite(l.widthM)) continue;
      if (Math.max(l.a.x, l.b.x) < minX || Math.min(l.a.x, l.b.x) > maxX || Math.max(l.a.z, l.b.z) < minZ || Math.min(l.a.z, l.b.z) > maxZ) continue;
      line([l.a, l.b], { stroke: "var(--taxi-pavement, #293748)", "stroke-width": Math.max(2, Math.min(80, l.widthM) * scale) });
    }
    line(onward, { stroke: "var(--taxi-route, #5aa2ff)", "stroke-width": 4, "stroke-dasharray": "5 5", "data-taxi-onward": "" });
    line(points, { stroke: amber, "stroke-width": 4, opacity: 0.35 });
    const ahead = line(points, { stroke: amber, "stroke-width": 4, "data-pushback-path": "" });
    const end = xy(finish);
    const finishMarker = svg("path", {
      d: plane,
      transform: "translate(" + end.join(",") + ") rotate(" + preview.headingDeg + ")",
      fill: "var(--taxi-ground, #141d28)",
      stroke: "var(--taxi-pushback, #e8b35c)",
      "stroke-width": 1.5,
      "data-pushback-final-heading": preview.headingDeg
    });
    const title = svg("text", { x: 16, y: 23, "font-size": 14 });
    svg("text", { x: 16, y: 283, fill: "var(--taxi-route, #5aa2ff)", "font-size": 12 }, "Then taxi \u2192 Runway " + preview.runway);
    const distance = svg("text", { x: 344, y: 283, "text-anchor": "end", "font-size": 12 });
    svg("text", { x: 341, y: 23, fill: "var(--taxi-aircraft, #e8eef5)", "text-anchor": "end", "font-size": 11 }, "N \u2191");
    const rail = { x1: 16, x2: 344, y1: 35, y2: 35, stroke: amber, "stroke-width": 2, "stroke-linecap": "round", "aria-hidden": true };
    const track = svg("line", rail), meter = svg("line", __spreadProps(__spreadValues({}, rail), { "stroke-dasharray": 328 }));
    return {
      id: preview.id,
      sceneKey: (_c = data.scene) == null ? void 0 : _c.key,
      background,
      ahead,
      finish: finishMarker,
      title,
      distance,
      track,
      meter,
      xy,
      coordinates,
      svg,
      aircraft: null,
      heading: 0
    };
  }

  // frontend/src/aircraft/pushback-controls.js
  function createPushbackControls({ send, changed, complete = () => {
  }, now = Date.now, setTimeout, clearTimeout }) {
    const prefix = "pushback-" + now() + "-" + Math.random().toString(36).slice(2) + "-";
    let context = {}, state = { active: false }, pending = "", pendingId = null, error = "", statusError = false;
    let sequence = 0, applied = 0, revision = 0, lastReply = -Infinity, nextStatus = 0, timer = null, destroyed = false, owned = false;
    const requests = /* @__PURE__ */ new Map();
    const usable = () => context.connected && context.visible !== false && context.enabled && context.profileKey;
    const active = () => Boolean(state.active || pending === "start");
    const fresh = () => now() - lastReply < 2e3;
    function snapshot() {
      var _a, _b, _c;
      const preview = context.preview || {}, plan = (_a = preview.data) == null ? void 0 : _a.pushbackPreview;
      const destination = /^[A-Z0-9]{3,8}$/.test(context.icao || "") && /^(0?[1-9]|[12][0-9]|3[0-6])[LRC]?$/.test(context.runway || "");
      const sameDestination = state.icao === context.icao && ((_b = state.runway) == null ? void 0 : _b.replace(/^0/, "")) === ((_c = context.runway) == null ? void 0 : _c.replace(/^0/, ""));
      const completed = !active() && ((plan == null ? void 0 : plan.phase) === "complete" || state.status === "complete" && sameDestination);
      const canStart = Boolean(usable() && !context.disabled && !active() && !pending && !completed && fresh() && state.canStart && destination && preview.fresh && (plan == null ? void 0 : plan.valid));
      const reason = error || (active() ? !fresh() ? "Waiting for pushback status\u2026" : state.reason : completed ? "Pushback complete. Follow the taxi guidance." : !context.enabled ? context.unavailableReason || "Pushback is unavailable on this connection." : !destination ? "Choose your departure airport and runway." : !fresh() ? "Waiting for live pushback status." : preview.loading ? "Finding pushback path\u2026" : preview.error || state.unavailableReason || (preview.data && !preview.fresh ? "Waiting for live pushback preview." : state.reason));
      return { state, active: active(), owned, pending, fresh: fresh(), completed, canStart, reason: reason || "" };
    }
    const publish = () => changed(snapshot());
    function reset() {
      revision++;
      requests.clear();
      state = { active: false };
      pending = "";
      pendingId = null;
      lastReply = -Infinity;
      applied = 0;
      owned = false;
      nextStatus = 0;
    }
    function request(operation) {
      var _a, _b;
      if (destroyed || !context.connected || operation !== "stop" && !usable()) return false;
      if (operation === "start" && !snapshot().canStart) return false;
      if (operation === "stop" && pending === "stop") return false;
      if (operation === "status" && [...requests.values()].some((r) => r.operation === "status")) return false;
      const requestId = prefix + revision + "-" + ++sequence, at = now();
      requests.set(requestId, { operation, at, sequence });
      if (operation !== "status") {
        applied = sequence;
        pending = operation;
        pendingId = requestId;
        error = "";
        statusError = false;
      }
      if (operation === "start") owned = true;
      const sent = send(__spreadValues({
        type: "pushback",
        operation,
        requestId,
        icao: context.icao,
        runway: context.runway,
        profileKey: context.profileKey,
        profileRevision: context.profileRevision
      }, operation === "start" ? { previewId: (_b = (_a = context.preview) == null ? void 0 : _a.data) == null ? void 0 : _b.pushbackPreview.id } : {}));
      if (sent === false) {
        requests.delete(requestId);
        if (pendingId === requestId) {
          pending = "";
          pendingId = null;
          error = "Pushback connection unavailable.";
        }
        if (operation === "start") owned = false;
      }
      publish();
      return sent !== false;
    }
    function tick() {
      timer = null;
      if (destroyed || !usable()) return;
      if (owned && active() && !fresh() && pending !== "stop") request("stop");
      requests.forEach((r, id) => {
        if (now() - r.at > (r.operation === "status" ? 2e3 : 15e3)) {
          requests.delete(id);
          if (id === pendingId) {
            pending = "";
            pendingId = null;
            error = "Pushback request timed out. Check the aircraft.";
          }
        }
      });
      if (now() >= nextStatus) {
        request("status");
        nextStatus = now() + (active() ? 250 : 1e3);
      }
      publish();
      timer = setTimeout(tick, 250);
    }
    function update(next) {
      if (destroyed) return;
      const wasUsable = usable(), previous = context;
      const normalized = __spreadProps(__spreadValues({}, next), { icao: String(next.icao || "").trim().toUpperCase(), runway: String(next.runway || "").trim().toUpperCase() });
      const changedAircraft = previous.profileKey !== normalized.profileKey || previous.profileRevision !== normalized.profileRevision;
      const leaving = !normalized.connected || normalized.visible === false || !normalized.enabled;
      if (owned && active() && (leaving || changedAircraft)) request("stop");
      context = normalized;
      if (changedAircraft || leaving) {
        const lostActive = owned && active() && !normalized.connected;
        reset();
        if (lostActive) error = "Connection lost. Pushback will stop; take control in the cockpit.";
      }
      if (!active() && (previous.icao !== context.icao || previous.runway !== context.runway || !wasUsable && usable())) error = "";
      if (!usable()) {
        if (timer !== null) clearTimeout(timer);
        timer = null;
      } else if (timer === null && !destroyed) {
        request("status");
        nextStatus = now() + 1e3;
        timer = setTimeout(tick, 250);
      }
      publish();
    }
    function receive(message) {
      if (destroyed || !usable() || (message == null ? void 0 : message.type) !== "pushbackState") return false;
      const r = requests.get(message.requestId);
      if (!r) return false;
      requests.delete(message.requestId);
      if (r.sequence < applied) {
        if (message.requestId === pendingId) {
          pending = "";
          pendingId = null;
          publish();
        }
        return true;
      }
      if (message.ok === false) {
        if (message.requestId === pendingId) {
          pending = "";
          pendingId = null;
        }
        if (r.operation === "start") owned = false;
        error = message.error || "Pushback request failed.";
        statusError = r.operation === "status";
        publish();
        return true;
      }
      if (message.currentProfileKey !== context.profileKey || message.currentProfileRevision !== context.profileRevision) return true;
      const wasActive = state.active;
      applied = r.sequence;
      state = message;
      lastReply = r.at;
      if (message.requestId === pendingId) {
        pending = "";
        pendingId = null;
      }
      if (!state.active) owned = false;
      if (state.active) nextStatus = Math.min(nextStatus, now() + 250);
      if (r.operation === "status" && statusError) {
        error = "";
        statusError = false;
      }
      publish();
      if (wasActive && message.status === "complete") complete();
      return true;
    }
    return { update, receive, request, snapshot, destroy() {
      if (owned && active()) request("stop");
      destroyed = true;
      if (timer !== null) clearTimeout(timer);
      timer = null;
      reset();
    } };
  }

  // frontend/src/aircraft/toolbar-taxi.js
  function createTaxiPanel({ document, send, setTimeout, clearTimeout, now = Date.now }) {
    const element = node("section", "card taxi-section");
    element.id = "toolbar-taxi";
    element.appendChild(node("h2", "card-title", "Taxi assistant"));
    element.appendChild(node("p", "muted", "Preview your pushback, then follow the route to the runway."));
    const fields = element.appendChild(node("div", "taxi-fields"));
    const airport = input("Airport ICAO", "taxi-airport", 8);
    const mode = select("Destination", "taxi-mode", [["runway", "Runway"], ["stand", "Stand / gate"]]);
    const runway = input("Runway", "taxi-runway", 3);
    const stand = select("Stand / gate", "taxi-stand", [["", "Load airport stands"]]);
    const actions = element.appendChild(node("div", "taxi-actions"));
    const push = button("Push back", "taxi-pushback-action", () => pushbackControls.request(pushback.active ? "stop" : "start"));
    push.addEventListener("keydown", (event) => {
      if (event.repeat && ["Enter", " "].includes(event.key)) event.preventDefault();
    });
    const pushbackReason = element.appendChild(node("p", "taxi-reason muted"));
    pushbackReason.id = "taxi-pushback-reason";
    pushbackReason.setAttribute("role", "status");
    push.setAttribute("aria-describedby", "taxi-pushback-reason");
    const load = button("Load stands", "taxi-load-stands", () => request("parkings"));
    const show = button("Show route", "taxi-show-route", () => request("preview"));
    const hide = button("Hide route", "taxi-hide-route", () => {
      invalidate();
      pushbackSelected = true;
      refresh();
    });
    const reason = element.appendChild(node("p", "taxi-reason muted"));
    reason.setAttribute("role", "status");
    const figure = element.appendChild(node("figure", "taxi-figure"));
    const pushbackView = node("button", "button button-quiet", "Pushback");
    pushbackView.id = "taxi-pushback-view";
    pushbackView.type = "button";
    figure.appendChild(pushbackView);
    pushbackView.addEventListener("click", () => {
      pushbackSelected = true;
      refresh();
    });
    const viewButton = node("button", "button button-quiet", "Overview");
    viewButton.id = "taxi-view";
    viewButton.type = "button";
    figure.appendChild(viewButton);
    viewButton.addEventListener("click", () => {
      if (pushbackSelected && departure.data) {
        pushbackSelected = false;
        overview = false;
      } else overview = !overview;
      refresh();
    });
    const map = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    map.setAttribute("viewBox", "0 0 360 300");
    map.setAttribute("role", "img");
    map.setAttribute("aria-label", "Taxi route");
    map.setAttribute("focusable", "false");
    figure.appendChild(map);
    const caption = figure.appendChild(node("figcaption", "taxi-caption"));
    const cautions = element.appendChild(node("p", "taxi-cautions"));
    element.appendChild(node("p", "taxi-note muted", "Routes use simulator scenery and may cross runways. Follow your ATC clearance and check traffic, obstacles and aircraft clearance."));
    const camera = createChaseCamera(), sprite = aircraftSprite(camera);
    const prefix = "taxi-" + now() + "-" + Math.random().toString(36).slice(2) + "-";
    let connection = {}, context = "", catalogue = {}, state = {}, route = null, scene = null;
    let overview = false, timer = null, sequence = 0, revision = 0, lastReply = -Infinity, error = "", standsLoaded = false, drawn = null;
    const pending = /* @__PURE__ */ new Map();
    let departure = { data: null, fresh: false }, pushbackSelected = true, planDefault = {};
    let pushback = { active: false, pending: "", canStart: false, state: {} };
    const pushbackControls = createPushbackControls({ send, now, setTimeout, clearTimeout, changed(snapshot) {
      if (snapshot.active && !pushback.active) {
        invalidate();
        pushbackSelected = true;
      }
      pushback = snapshot;
      refresh();
    } });
    const departurePreview = createDeparturePreview({ send, now, setTimeout, clearTimeout, changed(snapshot) {
      var _a, _b;
      const previous = (_a = departure.data) == null ? void 0 : _a.pushbackPreview.phase, phase = (_b = snapshot.data) == null ? void 0 : _b.pushbackPreview.phase;
      departure = snapshot;
      if (["connecting", "pushing", "stopping"].includes(phase) && !["connecting", "pushing", "stopping"].includes(previous)) {
        invalidate();
        pushbackSelected = true;
      }
      if (phase === "complete" && previous !== "complete") {
        invalidate();
        pushbackSelected = false;
      }
      updatePushback();
      refresh();
    } });
    function updateDeparture() {
      departurePreview.update({
        connected: connection.connected,
        visible: connection.visible,
        enabled: enabled() && simReady() && mode.control.value === "runway",
        profileKey: catalogue.profileKey,
        profileRevision: catalogue.profileRevision,
        icao: airport.control.value,
        runway: runway.control.value
      });
      updatePushback();
    }
    function updatePushback() {
      pushbackControls.update({
        connected: connection.connected,
        visible: connection.visible,
        enabled: enabled(),
        disabled: !simReady() || mode.control.value !== "runway" || has("preview") || has("parkings"),
        profileKey: catalogue.profileKey,
        profileRevision: catalogue.profileRevision,
        icao: airport.control.value,
        runway: runway.control.value,
        preview: departure
      });
    }
    function node(tag, className, text) {
      const n = document.createElement(tag);
      n.className = className || "";
      if (text !== void 0) n.textContent = text;
      return n;
    }
    function field(label2, control, id) {
      const wrapper = fields.appendChild(node("label", "taxi-field", label2));
      control.id = id;
      control.className = "taxi-value";
      wrapper.appendChild(control);
      return { control, wrapper };
    }
    function input(label2, id, maxLength) {
      const n = document.createElement("input");
      n.type = "text";
      n.maxLength = maxLength;
      n.autocomplete = "off";
      n.spellcheck = false;
      return field(label2, n, id);
    }
    function select(label2, id, choices) {
      const n = document.createElement("select");
      choices.forEach(([value, label3]) => {
        const option = node("option", "", label3);
        option.value = value;
        n.appendChild(option);
      });
      n.value = choices[0][0];
      return field(label2, n, id);
    }
    function button(label2, id, action) {
      const n = node("button", "button", label2);
      n.type = "button";
      n.id = id;
      n.addEventListener("click", action);
      actions.appendChild(n);
      return n;
    }
    function clear(target) {
      while (target.firstChild) target.removeChild(target.firstChild);
    }
    function invalidate() {
      revision++;
      pending.clear();
      route = null;
      scene = null;
      error = "";
    }
    function reset() {
      invalidate();
      state = {};
      lastReply = -Infinity;
      clearStands();
      pushbackControls.update({ connected: connection.connected, visible: false });
      departurePreview.reset();
    }
    function clearStands() {
      if (!standsLoaded) return;
      standsLoaded = false;
      clear(stand.control);
      const empty = node("option", "", "Load airport stands");
      empty.value = "";
      stand.control.appendChild(empty);
      stand.control.value = "";
    }
    [airport, runway].forEach(({ control }) => control.addEventListener("input", () => {
      invalidate();
      pushbackSelected = true;
      if (control === airport.control) clearStands();
      updateDeparture();
      refresh();
    }));
    [mode, stand].forEach(({ control }) => control.addEventListener("change", () => {
      invalidate();
      pushbackSelected = true;
      updateDeparture();
      refresh();
    }));
    function enabled() {
      return connection.connected && connection.visible && ["toolbar-presets", "full-control", "aircraft-control"].includes(connection.scope);
    }
    function simReady() {
      const s = connection.simState;
      return s && s.simconnectConnected === true && s.inMenu !== true && s.paused !== true && s.isPaused !== true;
    }
    function fresh() {
      return now() - lastReply < 2e3 && simReady();
    }
    function has(operation) {
      return Array.from(pending.values()).some((p) => p.operation === operation);
    }
    function validAirport() {
      return /^[A-Z0-9]{3,8}$/.test(airport.control.value.trim().toUpperCase());
    }
    function validDestination() {
      return mode.control.value === "stand" ? !!stand.control.value : /^(0?[1-9]|[12][0-9]|3[0-6])[LRC]?$/.test(runway.control.value.trim().toUpperCase());
    }
    function request(operation) {
      if (!enabled() || has(operation)) return;
      if (operation !== "status" && (!validAirport() || has("preview") || has("parkings") || pushback.active)) return;
      if (operation === "preview" && (!fresh() || state.canGuide !== true || !validDestination())) return;
      if (operation === "preview") {
        route = null;
        scene = null;
        pushbackSelected = false;
      }
      const requestId = prefix + ++sequence;
      const message = {
        type: "requestTaxiGuidance",
        operation,
        requestId,
        profileKey: catalogue.profileKey,
        profileRevision: catalogue.profileRevision
      };
      if (operation !== "status") message.icao = airport.control.value.trim().toUpperCase();
      if (operation === "preview") {
        if (mode.control.value === "stand") message.parking = stand.control.value;
        else message.runway = runway.control.value.trim().toUpperCase();
      }
      if (operation === "status" && state.sceneKey != null && (!scene || scene.key !== state.sceneKey)) message.scene = true;
      if (operation !== "status") error = "";
      if (send(message)) pending.set(requestId, { operation, revision, at: now() });
      else {
        state = {};
        lastReply = -Infinity;
        error = "Taxi guidance connection lost.";
      }
      updatePushback();
      refresh();
    }
    function poll() {
      timer = null;
      if (!enabled()) return;
      pending.forEach((p, id) => {
        if (now() - p.at >= (p.operation === "status" ? 2e3 : 12e3)) {
          pending.delete(id);
          if (p.operation !== "status") error = "Taxi guidance request timed out. Try again.";
        }
      });
      request("status");
      refresh();
      timer = setTimeout(poll, route || has("preview") ? 500 : 1e3);
    }
    function update(next) {
      const c = next.profile && next.profile.controlCapabilities && next.profile.controlCapabilities.aircraftCommands || {};
      const key = c.profileKey + ":" + c.profileRevision;
      if (key !== context || !next.connected) {
        reset();
        context = key;
      }
      const wasEnabled = enabled();
      connection = next;
      catalogue = c;
      const plan = next.plan || {};
      if (!pushback.active && mode.control.value === "runway" && (plan.origin !== planDefault.origin || plan.departureRunway !== planDefault.departureRunway)) {
        const previousAirport = airport.control.value, previousRunway = runway.control.value;
        if (!airport.control.value || airport.control.value === planDefault.origin) airport.control.value = plan.origin || "";
        if (airport.control.value === plan.origin && (!runway.control.value || runway.control.value === planDefault.departureRunway)) runway.control.value = plan.departureRunway || "";
        if (airport.control.value !== previousAirport || runway.control.value !== previousRunway) {
          if (airport.control.value !== previousAirport) clearStands();
          invalidate();
          pushbackSelected = true;
        }
      }
      planDefault = plan;
      updateDeparture();
      if (!enabled()) {
        if (timer !== null) clearTimeout(timer);
        timer = null;
        pending.clear();
        lastReply = -Infinity;
      } else if (!wasEnabled) poll();
      if (next.visible) refresh();
    }
    function receive(message) {
      if (pushbackControls.receive(message)) return;
      if (departurePreview.receive(message)) return;
      if (message.type !== "toolbarTaxiState" || !enabled()) return;
      const p = pending.get(message.requestId);
      if (!p || p.revision !== revision) return;
      pending.delete(message.requestId);
      if (message.ok !== true) {
        error = message.error || "Taxi guidance unavailable.";
        if (p.operation === "status") {
          state = {};
          lastReply = -Infinity;
        }
        refresh();
        return;
      }
      if (message.currentProfileKey !== catalogue.profileKey || message.currentProfileRevision !== catalogue.profileRevision) {
        reset();
        refresh();
        return;
      }
      if (p.operation === "parkings") {
        clearStands();
        const options = message.standOptions || (message.stands || []).map((label2) => ({ label: label2 }));
        standsLoaded = options.length > 0;
        options.forEach((item) => {
          const n = node("option", "", item.label + (item.typeLabel ? " \xB7 " + item.typeLabel : ""));
          n.value = item.label;
          stand.control.appendChild(n);
        });
        if (!options.length) error = "No stands found in this airport scenery.";
        refresh();
        return;
      }
      if (p.operation === "preview") {
        pending.forEach((value, id) => {
          if (value.operation === "status") pending.delete(id);
        });
        route = message.preview || null;
      } else if (route && (!message.sceneKey || !scene || message.sceneKey !== scene.key)) route = null;
      if (message.scene) scene = message.scene;
      else if (scene && scene.key !== message.sceneKey) scene = null;
      state = message;
      lastReply = p.at;
      error = "";
      updatePushback();
      refresh();
    }
    function refresh() {
      var _a, _b, _c, _d;
      const busy = has("preview") || has("parkings") || pushback.active;
      [airport, runway, mode, stand].forEach(({ control }) => {
        control.disabled = pushback.active;
      });
      push.hidden = !pushback.active && (mode.control.value !== "runway" || pushback.completed);
      push.disabled = pushback.active ? pushback.pending === "stop" : !pushback.canStart;
      push.textContent = pushback.active ? pushback.pending === "stop" ? "Stopping\u2026" : "Stop pushback" : "Push back";
      push.className = "button taxi-pushback-action" + (pushback.active ? " taxi-pushback-stop" : "");
      pushbackReason.hidden = !pushback.active && mode.control.value !== "runway";
      pushbackReason.className = "taxi-reason " + (pushback.completed ? "taxi-complete" : "muted");
      pushbackReason.textContent = (pushback.active && pushback.fresh && Number.isFinite(pushback.state.remainingM) ? Math.round(pushback.state.remainingM) + " m remaining \xB7 Runway " + pushback.state.runway + ". " : "") + (pushback.reason || "");
      runway.wrapper.hidden = mode.control.value === "stand";
      stand.wrapper.hidden = mode.control.value !== "stand";
      load.hidden = mode.control.value !== "stand";
      load.disabled = !enabled() || !validAirport() || busy;
      show.disabled = !enabled() || !fresh() || !state.canGuide || !validAirport() || !validDestination() || busy;
      show.textContent = has("preview") ? "Finding route\u2026" : route || ((_a = departure.data) == null ? void 0 : _a.pushbackPreview.phase) === "complete" ? "Refresh route" : "Show route";
      load.textContent = has("parkings") ? "Loading stands\u2026" : "Load stands";
      hide.hidden = !route && !has("preview");
      hide.textContent = departure.data ? "Back to pushback" : "Hide route";
      const unavailable = !connection.connected ? "Connect FlightFabric to view taxi guidance." : !enabled() ? "Taxi guidance is unavailable on this connection." : !fresh() ? "Waiting for fresh aircraft position on the ground." : state.guidanceUnavailableReason || "";
      const completed = departure.fresh && ((_b = departure.data) == null ? void 0 : _b.pushbackPreview.phase) === "complete";
      reason.textContent = (pushbackSelected && departure.data ? "" : error) || unavailable || (has("preview") || has("parkings") ? "Loading airport guidance\u2026" : completed && !pushback.completed ? "Pushback complete. Follow the taxi guidance." : "");
      reason.className = "taxi-reason " + (completed && !error && !unavailable && !busy ? "taxi-complete" : "muted");
      reason.hidden = !reason.textContent;
      const displayRoute = route || ((_c = departure.data) == null ? void 0 : _c.route), displayScene = route ? scene : (_d = departure.data) == null ? void 0 : _d.scene;
      figure.hidden = !displayRoute;
      cautions.hidden = !displayRoute;
      pushbackView.hidden = !departure.data;
      const pushing = !!(pushbackSelected && departure.data);
      pushbackView.setAttribute("aria-pressed", String(pushing));
      if (!displayRoute || !connection.visible) return;
      if (pushing) {
        drawn = null;
        viewButton.textContent = "Route ribbon";
        viewButton.disabled = false;
        renderPushbackMap(map, departure.data, departure.fresh);
        caption.textContent = pushbackCaption(departure.data, departure.fresh);
        cautions.hidden = true;
        return;
      }
      map.removeAttribute("data-pushback-map");
      const poseSource = route ? fresh() ? state.aircraft : null : departure.fresh ? departure.data.aircraft : null;
      const a = poseSource && [poseSource.x, poseSource.z, poseSource.headingDeg].every(Number.isFinite) ? poseSource : null;
      renderRoute(displayRoute, displayScene, a);
    }
    function renderRoute(route2, scene2, a) {
      var _a;
      const progress = splitRoute(route2.points, a), end = route2.points[route2.points.length - 1];
      const offRoute = progress.distanceM > 25;
      const arrived = a && Math.hypot(end.x - a.x, end.z - a.z) <= 5;
      const remaining = a && !offRoute ? progress.ahead.reduce((sum, p, i, points) => sum + (i ? Math.hypot(p.x - points[i - 1].x, p.z - points[i - 1].z) : 0), progress.distanceM) : null;
      const destination = route2.kind === "stand" ? route2.label : "holding point before runway " + route2.runway;
      caption.textContent = !a ? "Reference only \xB7 Live aircraft position unavailable." : offRoute ? "Off route \xB7 Check your position or show a new route." : arrived ? route2.kind === "stand" ? "At " + destination : "At holding point \xB7 Hold short of runway " + route2.runway : Math.round(remaining) + " m to " + destination;
      if (a && route2 === ((_a = departure.data) == null ? void 0 : _a.route) && departure.data.pushbackPreview.phase !== "complete") caption.textContent = "Taxi route after pushback to runway " + route2.runway + ". You control the aircraft.";
      cautions.textContent = [
        route2.runwayTravelM > 1 ? "Includes " + Math.round(route2.runwayTravelM) + " m along an intervening runway." : "",
        route2.joinM >= 1 ? "The first " + Math.round(route2.joinM) + " m cross open ground to reach the centreline. Check for obstacles." : ""
      ].filter(Boolean).join(" ");
      cautions.hidden = !cautions.textContent;
      viewButton.textContent = overview ? "Follow aircraft" : "Overview";
      viewButton.disabled = !a;
      map.setAttribute("aria-label", "Taxi route to " + destination + ". " + caption.textContent);
      const pose = a ? [a.x, a.z, a.headingDeg].join(":") : "";
      if (drawn && drawn.route === route2 && drawn.scene === scene2 && drawn.overview === overview && drawn.pose === pose) return;
      drawn = { route: route2, scene: scene2, overview, pose };
      clear(map);
      if (a && !overview) drawChase(a, route2, scene2);
      else drawOverview(a, route2, scene2);
    }
    function svg(tag, attributes, text) {
      const n = document.createElementNS("http://www.w3.org/2000/svg", tag);
      Object.keys(attributes).forEach((key) => n.setAttribute(key, attributes[key]));
      if (text !== void 0) n.textContent = text;
      map.appendChild(n);
      return n;
    }
    function path(d, className, attrs = {}) {
      if (d) svg("path", Object.assign({ d, class: className }, attrs));
    }
    function drawChase(a, route2, scene2) {
      const parts = splitRoute(smoothRoute(route2.points), a);
      const projected = projectTaxiScene(camera, { scene: scene2, route: route2, aircraft: a, done: parts.done, ahead: parts.ahead });
      path(projected.pavement.taxi, "taxi-pavement");
      path(projected.pavement.runway, "taxi-runway");
      projected.runways.forEach((rw) => {
        path(rw.slab, "taxi-runway");
        path(rw.dashes, "taxi-marking");
        rw.labels.forEach((l) => svg("text", { x: l.x, y: l.y, "font-size": l.size, class: "taxi-map-label", "text-anchor": "middle" }, l.text));
      });
      path(projected.centrelines.taxi, "taxi-centreline");
      projected.stands.forEach((st) => {
        path(st.d, "taxi-stand");
        if (st.label) svg("text", { x: st.label.x, y: st.label.y, "font-size": st.label.size, class: "taxi-map-label", "text-anchor": "middle" }, st.label.text);
      });
      path(projected.route.done, "taxi-done");
      path(projected.route.glow, "taxi-glow");
      path(projected.route.ahead, "taxi-ahead");
      if (projected.hold) {
        path(projected.hold.dash, "taxi-ahead");
        path(projected.hold.bar, "taxi-hold");
      }
      path(projected.destinationStand, "taxi-destination");
      path(projected.stop, "taxi-stop");
      path(sprite.shadow, "taxi-shadow");
      sprite.faces.forEach((face) => path(face.d, "", { fill: face.fill, stroke: "var(--taxi-ground)", "stroke-width": 0.5 }));
    }
    function drawOverview(a, route2, scene2) {
      const points = route2.points.concat(route2.holdShort ? [route2.holdShort] : [], a ? [a] : []);
      const xs = points.map((p) => p.x), zs = points.map((p) => p.z);
      const minX = Math.min(...xs), maxX = Math.max(...xs), minZ = Math.min(...zs), maxZ = Math.max(...zs);
      const scale = Math.min(312 / Math.max(50, maxX - minX), 252 / Math.max(50, maxZ - minZ));
      const xy = (p) => [180 + (p.x - (minX + maxX) / 2) * scale, 150 - (p.z - (minZ + maxZ) / 2) * scale];
      const line = (ps) => ps.map((p, i) => (i ? "L" : "M") + xy(p).join(",")).join("");
      (scene2 && scene2.links || []).forEach((l) => path(line([l.a, l.b]), "taxi-overview-pavement", { "stroke-width": Math.max(1, l.widthM * scale) }));
      path(line(route2.points), "taxi-overview-route");
      const end = xy(route2.points[route2.points.length - 1]);
      svg("circle", { cx: end[0], cy: end[1], r: 5, class: "taxi-stop" });
      if (a) {
        const p = xy(a);
        svg("path", { d: "M0,-8L5,6L0,3L-5,6Z", class: "taxi-marker", transform: "translate(" + p.join(",") + ") rotate(" + a.headingDeg + ")" });
      }
    }
    refresh();
    return { element, update, receive, reset, destroy() {
      pushbackControls.destroy();
      connection = {};
      reset();
      departurePreview.destroy();
      if (timer !== null) clearTimeout(timer);
      timer = null;
    } };
  }
  return __toCommonJS(toolbar_taxi_exports);
})();
